name: Publish Package

on:
  workflow_run:
    workflows:
      - 'Update Changelog'
    types:
      - completed
  push:
    tags:
      '*-beta*'

jobs:
  publish:
    name: Publish Package
    runs-on: [self-hosted, ubuntu22]

    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: 'Fix permissions'
        run: sudo -S chown -R $USER:$USER $GITHUB_WORKSPACE

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install NPM Packages
        run: npm ci

      - name: Run CHG Project Scorecard
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        uses: chghealthcare/chg-scorecard-github-action-tool@v1
        with:
          github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Publish Package
        run: |
          echo "@chghealthcare:registry=https://npm.pkg.github.com/chghealthcare" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
          npm publish
          rm -f .npmrc

      - name: get-package-version
        run: echo "PACKAGE_VERSION=$(cat package.json | jq -r '.version')" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.PACKAGE_VERSION }}
          commit: ${{ github.sha }}
          generateReleaseNotes: true

      - name: Force workspace to clean
        if: always()
        run: |
          (cd $GITHUB_WORKSPACE && sudo git clean -xdf) || echo "Could not clean up ignored files and directories"